name = "network-trainer"
packages = [ "legoeducation","numpy"]

[files]
"https://raw.githubusercontent.com/tuftsceeo/NeuralNetworkEducation/refs/heads/main/Webpages/network-trainer/Device.py" = ""
"https://raw.githubusercontent.com/tuftsceeo/NeuralNetworkEducation/refs/heads/main/Webpages/network-trainer/index.html" = ""
"https://raw.githubusercontent.com/tuftsceeo/NeuralNetworkEducation/refs/heads/main/Webpages/network-trainer/main.py" = ""
"https://raw.githubusercontent.com/tuftsceeo/NeuralNetworkEducation/refs/heads/main/Webpages/network-trainer/plots/fit_plot.py" = ""
"https://raw.githubusercontent.com/tuftsceeo/NeuralNetworkEducation/refs/heads/main/Webpages/network-trainer/plots/live_plot.py" = ""
"https://raw.githubusercontent.com/tuftsceeo/NeuralNetworkEducation/refs/heads/main/Webpages/network-trainer/plots/plot_utils.py" = ""
"https://raw.githubusercontent.com/tuftsceeo/NeuralNetworkEducation/refs/heads/main/Webpages/network-trainer/plots/loss_plot.py" = ""
"https://raw.githubusercontent.com/tuftsceeo/NeuralNetworkEducation/refs/heads/main/Webpages/network-trainer/plots/scatter_plot.py" = ""
"https://raw.githubusercontent.com/tuftsceeo/NeuralNetworkEducation/refs/heads/main/Webpages/network-trainer/network/activation_editor.py" = ""
"https://raw.githubusercontent.com/tuftsceeo/NeuralNetworkEducation/refs/heads/main/Webpages/network-trainer/network/activations.py" = ""
"https://raw.githubusercontent.com/tuftsceeo/NeuralNetworkEducation/refs/heads/main/Webpages/network-trainer/network/network_actions.py" = ""
"https://raw.githubusercontent.com/tuftsceeo/NeuralNetworkEducation/refs/heads/main/Webpages/network-trainer/network/network_model.py" = ""
"https://raw.githubusercontent.com/tuftsceeo/NeuralNetworkEducation/refs/heads/main/Webpages/network-trainer/misc_ui/arrows.py" = ""
"https://raw.githubusercontent.com/tuftsceeo/NeuralNetworkEducation/refs/heads/main/Webpages/network-trainer/misc_ui/dataset_ui.py" = ""
"https://raw.githubusercontent.com/tuftsceeo/NeuralNetworkEducation/refs/heads/main/Webpages/network-trainer/misc_ui/templates.py" = ""
"https://raw.githubusercontent.com/tuftsceeo/NeuralNetworkEducation/refs/heads/main/Webpages/network-trainer/misc_ui/ui_chrome.py" = ""
"https://raw.githubusercontent.com/tuftsceeo/NeuralNetworkEducation/refs/heads/main/Webpages/network-trainer/glue/bindings.py" = ""
"https://raw.githubusercontent.com/tuftsceeo/NeuralNetworkEducation/refs/heads/main/Webpages/network-trainer/glue/state.py" = ""
"https://raw.githubusercontent.com/tuftsceeo/NeuralNetworkEducation/refs/heads/main/Webpages/network-trainer/glue/sync.py" = ""

[js_modules.main]
"https://cdn.jsdelivr.net/gh/tuftsceeo/NeuralNetworkEducation@main/Webpages/network-trainer/JS/ble.js" = "ble"
"https://cdn.jsdelivr.net/gh/tuftsceeo/NeuralNetworkEducation@main/Webpages/network-trainer/JS/plotly.js" = "Plotly"
